---
title: "CONTRIBUTING"
author: "Ellen Talbot"
date: "03/10/2019"
output: html_document
---

# Contributing to reportfactory

Contributions are welcomed by pull request from everybody.

# How to contribute

Third-party patches are essential for keeping RECON great. We want to keep it as easy as possible to contribute changes that get things working in your environment. There are a few guidelines that we need contributors to follow so that we can have a chance of keeping on top of things.

## Getting Started
* Make sure you have a [GitHub account](https://github.com/signup/free).
* Submit an issue if one does not already exist.
  * Clearly describe the issue including steps to reproduce when it is a bug.
  * Make sure you fill in the earliest version that you know has the issue.
  * An issue is not necessary for trivial changes (see below)
* Fork the repository on GitHub.

## Making Changes

* Create a topic branch from where you want to base your work.
  * This is usually the master branch.
  * Only target release branches if you are certain your fix must be on that
    branch.
  * To quickly create a topic branch based on master, run `git checkout -b
    fix/master/my_contribution master`. Please avoid working directly on the
    `master` branch.
* Make commits of logical and atomic units.
* Check for unnecessary whitespace with `git diff --check` before committing.
* Make sure your commit messages are in the proper format. If the commit
  addresses an issue, start the first line of the commit with the issue number in parentheses.
* Make sure you have added the necessary tests for your changes.


## Making Trivial Changes

Trivial changes include but are not limited to:
* Spelling / grammar fixes.
* Correcting typos like the transposition of letters in a variable name.
* Cleaning up comments in the code.
* Changes to white space or formatting.
* Patches that are purely deletions, such as removal of duplicate information or code that never executes.

For changes of a trivial nature it is not always necessary to create a new issue. In this case, it is appropriate to start the first line of a commit with one of  `(docs)`, `(maint)`, or `(packaging)` instead of an issue number.

For commits that address trivial repository maintenance tasks or packaging
issues, start the first line of the commit with `(maint)` or `(packaging)`,
respectively.

## Submitting Changes

* Push your changes to a topic branch in your fork of the repository.
* Submit a pull request to the repository in the RECON organization.
* Update your issue and indicate that it is ready for review
* The core team looks at Pull Requests on a regular basis
* After feedback has been given we expect responses within two weeks. After two
  weeks we may close the pull request if it isn't showing any activity.

## Revert Policy

By running tests in advance and by engaging with peer review for prospective
changes, your contributions have a high probability of becoming long lived
parts of the the project. After being merged, the code will run through a
series of testing pipelines on a large number of operating system
environments. These pipelines can reveal incompatibilities that are difficult
to detect in advance.

If the code change results in a test failure, we will make our best effort to
correct the error. If a fix cannot be determined and committed within 24 hours
of its discovery, the commit(s) responsible _may_ be reverted, at the
discretion of the committer and maintainers. This action would be taken
to help maintain passing states in our testing pipelines.

The original contributor will be notified of the revert. A reference to the test(s) and operating system(s) that failed as a result of the code change will also be noted. This test(s) should be used to check future submissions of the code to ensure the issue has been resolved.

### Summary

* Changes resulting in test pipeline failures will be reverted if they cannot
  be resolved within one business day.
  
## Semantic Versioning

See [here](https://semver.org) and [here](https://medium.com/@jameshamann/a-brief-guide-to-semantic-versioning-c6055d87c90e) for semantic versioning guidelines in full.

*0 — Pre-MVP/Alpha*
At this stage, you’re developing your app and still building towards an MVP. There’s no real point differentating between versions here because it’s not a useable product yet. During this period, the version will remain at 0.

*Major.Minor.Patch — Alpha/Beta*
Once you reach your MVP, you might iterate over this and create Alpha/Beta releases for users to test and supply feedback on. When creating your first release, you’ll want to start versioning. This helps you keep track of your app and creates a timeline of what features were added when and what bugs have and have not been fixed yet. You might be wondering, what exactly constitutes a major, minor or patch release.
_Major Release_ — Increment the first digit by 1 if the new features break backwards compatibility/current features
_Minor Release_ — Increment the middle digit by 1 if the new features don’t break any existing features and are compatible with the app in it’s current state.
_Patch Release_ — Increment the last digit by 1 if you’re publishing bug/patch fixes to your app.

Before publishing your first, useable version, you might find yourself incrementing the middle and the last digit to keep track of Alpha/Beta releases. Only once you’re ready for a proper, first release, should you start versioning from 1.0.0.

## Changelog 
The NEWS.md file should be updated using the guiding principles to include the following information on each version:

_Guiding Principles_
- Changelogs are for humans, not machines.
- There should be an entry for every single version.
- The same types of changes should be grouped.
- Versions and sections should be linkable.
- The latest version comes first.
- The release date of each version is displayed.
- Mention whether you follow Semantic Versioning.

_Types of changes_
- Added for new features.
- Changed for changes in existing functionality.
- Deprecated for soon-to-be removed features.
- Removed for now removed features.
- Fixed for any bug fixes.
- Security in case of vulnerabilities.

## Additional Resources

* [General GitHub documentation](https://help.github.com/)
* [GitHub pull request documentation](https://help.github.com/articles/creating-a-pull-request/)
