#' Create a new factory with random name
#'
#' This function is a wrapper for \code{\link{new_factory}} which creates a new
#' factory with a random label, in a specified location. The label itself is
#' generated by choosing a user-defined number of random alphanumeric
#' characters.
#'
#'
#' @param path the path where the new factory should be created
#'
#' @param prefix a `character` indicating the prefix to be used to name the
#'   factory
#' 
#' @param n the number of random alphanumeric characters to use; defaults to 6.
#'
#' @param ... further arguments passed to \code{\link{new_factory}}
#'
#' @export
#'
#' @author Thibaut Jombart \email{thibautjombart@@gmail.com}
#'
#' @seealso \code{\link{new_factory}} to create new factories with
#'   user-specified labels.

random_factory <- function(path = getwd(),
                           prefix = "factory",
                           n = 6, ...) {
  id <- random_alphanum(n)
  factory_name <- paste(prefix, id, sep = "_")
  factory_name <- sub("^_", "", factory_name) # in case prefix is empty
  destination <- file.path(path, factory_name)
  new_factory(destination, ...)
}
