#' Create a new factory with random name
#'
#' This function is a wrapper for \code{\link{new_factory}} which creates a new
#' factory with a random label. The label itself is generated by choosing a
#' user-defined number of random alphanumeric characters.
#'
#'
#' @param n the number of random alphanumeric characters to use; defaults to 12.
#'
#' @param ... further arguments passed to \code{\link{new_factory}}
#'
#' @export
#'
#' @author Thibaut Jombart \email{thibautjombart@@gmail.com}
#'
#' @seealso \code{\link{new_factory}} to create new factories with
#'   user-specified labels.

random_factory <- function(n = 12, ...) {
  dict <- c(letters, LETTERS, 0:10)
  id <- paste(sample(dict, n, replace = TRUE), collapse = "")
  destination <- paste("factory", id, sep = "_")
  new_factory(destination, ...)
}

